---
name: download stylua
run-name: download stylua-${{inputs.version}} from official release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: version to build (without "v")
        default: 0.18.2
        type: string

permissions: write-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-aarch64
            name: darwin-arm64
          - platform: macos-x86_64
            name: darwin-amd64
    name: Download ${{matrix.platform}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Download
        run: |
          curl -sSLf -o stylua.zip "https://github.com/JohnnyMorganz/StyLua/releases/download/v${{inputs.version}}/stylua-${{matrix.platform}}.zip"
          unzip stylua.zip
      - name: Upload ${{matrix.name}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tar -czf "stylua-v${{inputs.version}}-${{matrix.name}}.tar.gz" stylua
          # create release if not exist
          gh release create "v${{inputs.version}}" --notes "Release stylua v${{inputs.version}}" --title "v${{inputs.version}}" --repo "${{github.repository}}" || true
          # delete the asset if exists
          gh release delete-asset "v${{inputs.version}}" "stylua-v${{inputs.version}}-${{matrix.name}}.tar.gz" --yes --repo "${{github.repository}}" || true
          gh release upload "v${{inputs.version}}" "./stylua-v${{inputs.version}}-${{matrix.name}}.tar.gz" --repo "${{github.repository}}"
